pergunta = input('Qual o seu Nome?')
print('Olá', pergunta,'!','Prazer em te conhecer!')
print('Agora, me diga a sua Data de Nascimento')
dia = input('Dia =')
mes = input('Mês =')
ano = input('Ano =')
print('Você nasceu no dia', dia,'do Mês', mes,'Do ano', ano,'Correto?')
primeironumero = input('Primeiro Número')
segundonumero = input('Segundo Número')
print('A soma é',primeironumero + segundonumero)