a = input('Digite Algo: ')
print('O tipo Primitivo desse valor é: {} '.format(type(a)))
print('é um Alfanumerico? {}'.format(a.isalnum()))
print('é um Alfábetico? {}'.format(a.isalpha()))
print('é um Número? {}'.format(a.isnumeric()))
print('Só tem Espaços? {}'.format(a.isspace()))
print('é um printável? {}'.format(a.isprintable()))
print('Está em Maiusculo? {}'.format(a.isupper()))
print('Está em Minusculo? {}'.format(a.islower()))
print('Está capitalizado? {}'.format(a.istitle()))
